spring.application.name=pos

spring.datasource.url=jdbc:mysql://localhost:3306/controlventadb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración opcional de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-null-for-primitives=false